//! Station database bootstrap functionality.
//!
//! This module provides functionality to bootstrap the locations database
//! with known airport/station data. The data comes from NOAA/FAA sources
//! and is embedded in the binary for initial population.
//!
//! ## Data Sources
//!
//! - US airports: FAA NASR data, filtered to IFR/VFR airports with ICAO codes
//! - Additional stations can be loaded from external files
//!
//! ## Bootstrap Process
//!
//! 1. Check if locations table is empty or has fewer than threshold entries
//! 2. If so, load embedded station data and insert into database
//! 3. Mark all bootstrap locations as type "airport" with country "US"

use crate::observations::{Location, ObservationCatalog};
use tracing::{debug, info, warn};
use wms_common::WmsResult;

/// Embedded station data for US airports.
///
/// Format: ICAO_ID,NAME,LATITUDE,LONGITUDE,ELEVATION_M
/// This is a subset of ~5000 US airports with ICAO codes.
///
/// Data derived from FAA NASR and filtered to airports likely to report METARs.
const EMBEDDED_STATIONS_CSV: &str = include_str!("../data/us_airports.csv");

/// Embedded US populated places (Census Gazetteer coords + PEP population).
///
/// Format: id,name,lon,lat,elevation_m,state,population
/// Generated by scripts/build_populated_places.py. Loaded into the `locations`
/// table with location_type='populated_place' to power the EDR `populated`
/// collection.
const EMBEDDED_POPULATED_PLACES_CSV: &str = include_str!("../data/us_populated_places.csv");

/// Bootstrap the locations database with known airport data.
///
/// This will only populate the database if it has fewer than `min_threshold`
/// locations. Set `min_threshold` to 0 to always skip, or a high number to
/// always populate.
///
/// Returns the number of locations inserted.
pub async fn bootstrap_locations(
    catalog: &ObservationCatalog,
    min_threshold: i64,
) -> WmsResult<usize> {
    // Check current location count
    let current_count = catalog.count_locations().await?;

    if current_count >= min_threshold {
        debug!(
            current = current_count,
            threshold = min_threshold,
            "Skipping station bootstrap - already have enough locations"
        );
        return Ok(0);
    }

    info!(
        current = current_count,
        threshold = min_threshold,
        "Bootstrapping locations database with airport data"
    );

    // Parse embedded CSV data
    let locations = parse_stations_csv(EMBEDDED_STATIONS_CSV)?;

    info!(count = locations.len(), "Parsed airport station data");

    // Insert locations in batches
    let mut inserted = 0;
    for chunk in locations.chunks(100) {
        inserted += catalog.upsert_locations(chunk).await?;
    }

    info!(inserted = inserted, "Bootstrap complete");
    Ok(inserted)
}

/// Parse station data from CSV format.
///
/// Expected format: ICAO_ID,NAME,LONGITUDE,LATITUDE,ELEVATION_M,STATE
/// Note: Longitude comes before Latitude (matches GeoJSON convention)
/// Lines starting with # are comments.
fn parse_stations_csv(csv_data: &str) -> WmsResult<Vec<Location>> {
    let mut locations = Vec::new();

    for (line_num, line) in csv_data.lines().enumerate() {
        let line = line.trim();

        // Skip empty lines and comments
        if line.is_empty() || line.starts_with('#') {
            continue;
        }

        let parts: Vec<&str> = line.split(',').collect();
        if parts.len() < 4 {
            warn!(
                line = line_num + 1,
                content = line,
                "Skipping malformed station line"
            );
            continue;
        }

        let icao = parts[0].trim();
        let name = parts[1].trim();
        // CSV format is LON,LAT (GeoJSON convention)
        let lon: f64 = match parts[2].trim().parse() {
            Ok(v) => v,
            Err(_) => {
                warn!(
                    line = line_num + 1,
                    icao = icao,
                    "Invalid longitude, skipping"
                );
                continue;
            }
        };
        let lat: f64 = match parts[3].trim().parse() {
            Ok(v) => v,
            Err(_) => {
                warn!(
                    line = line_num + 1,
                    icao = icao,
                    "Invalid latitude, skipping"
                );
                continue;
            }
        };

        let elevation_m: Option<f32> = if parts.len() > 4 {
            parts[4].trim().parse().ok()
        } else {
            None
        };

        // Get state/region if provided (column 5)
        let region: Option<String> = if parts.len() > 5 {
            let r = parts[5].trim();
            if !r.is_empty() {
                Some(r.to_string())
            } else {
                None
            }
        } else {
            None
        };

        let mut location = Location::new(icao, name, lon, lat)
            .with_type("airport")
            .with_country("US");

        if let Some(elev) = elevation_m {
            location = location.with_elevation(elev);
        }

        if let Some(reg) = region {
            location = location.with_region(reg);
        }

        locations.push(location);
    }

    Ok(locations)
}

/// Bootstrap the locations database with US populated places.
///
/// Idempotent: only populates when the count of existing populated_place rows
/// is below `min_threshold`. Set `min_threshold` to 0 to skip. Populated places
/// live in the shared `locations` table with location_type='populated_place'
/// and population stored in properties->>'population'.
///
/// Returns the number of places inserted.
pub async fn bootstrap_populated_places(
    catalog: &ObservationCatalog,
    min_threshold: i64,
) -> WmsResult<usize> {
    let current = catalog.count_locations_by_type("populated_place").await?;

    if current >= min_threshold {
        debug!(
            current,
            threshold = min_threshold,
            "Skipping populated-places bootstrap - already populated"
        );
        return Ok(0);
    }

    info!(
        current,
        threshold = min_threshold,
        "Bootstrapping locations database with US populated places"
    );

    let places = parse_populated_places_csv(EMBEDDED_POPULATED_PLACES_CSV)?;
    info!(count = places.len(), "Parsed populated-places data");

    let mut inserted = 0;
    for chunk in places.chunks(500) {
        inserted += catalog.upsert_locations(chunk).await?;
    }

    info!(inserted, "Populated-places bootstrap complete");
    Ok(inserted)
}

/// Parse populated-places CSV.
///
/// Format: id,name,lon,lat,elevation_m,state,population
/// Lines starting with # (and the header row) are skipped. Population is stored
/// in the JSON properties; state becomes the region.
fn parse_populated_places_csv(csv_data: &str) -> WmsResult<Vec<Location>> {
    let mut places = Vec::new();

    for (line_num, line) in csv_data.lines().enumerate() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        // Skip header row
        if line.starts_with("id,") {
            continue;
        }

        // CSV split that respects double-quoted fields (place names can
        // contain commas, e.g. "Islamorada, Village of Islands").
        let parts = split_csv_line(line);
        if parts.len() < 7 {
            warn!(
                line = line_num + 1,
                content = line,
                "Skipping malformed place line"
            );
            continue;
        }

        let id = parts[0].trim();
        let name = parts[1].trim();
        let lon: f64 = match parts[2].trim().parse() {
            Ok(v) => v,
            Err(_) => {
                warn!(line = line_num + 1, id, "Invalid longitude, skipping");
                continue;
            }
        };
        let lat: f64 = match parts[3].trim().parse() {
            Ok(v) => v,
            Err(_) => {
                warn!(line = line_num + 1, id, "Invalid latitude, skipping");
                continue;
            }
        };
        let elevation_m: Option<f32> = parts[4].trim().parse().ok();
        let state = parts[5].trim();
        let population: Option<i64> = parts[6].trim().parse().ok();

        let mut location = Location::new(id, name, lon, lat)
            .with_type("populated_place")
            .with_country("US");

        if let Some(elev) = elevation_m {
            location = location.with_elevation(elev);
        }
        if !state.is_empty() {
            location = location.with_region(state);
        }
        if let Some(pop) = population {
            location = location.with_property("population", serde_json::Value::Number(pop.into()));
        }
        if !state.is_empty() {
            location =
                location.with_property("state", serde_json::Value::String(state.to_string()));
        }

        places.push(location);
    }

    Ok(places)
}

/// Split a CSV line into fields, honoring double-quoted fields that may
/// contain commas. Minimal RFC-4180-style handling (no escaped quotes needed
/// for this dataset).
fn split_csv_line(line: &str) -> Vec<String> {
    let mut fields = Vec::new();
    let mut current = String::new();
    let mut in_quotes = false;

    for c in line.chars() {
        match c {
            '"' => in_quotes = !in_quotes,
            ',' if !in_quotes => {
                fields.push(std::mem::take(&mut current));
            }
            _ => current.push(c),
        }
    }
    fields.push(current);
    fields
}

/// Load additional stations from a file path.
///
/// This can be used to supplement the embedded data with additional
/// stations from external sources.
pub async fn load_stations_from_file(
    catalog: &ObservationCatalog,
    file_path: &str,
) -> WmsResult<usize> {
    let csv_data = tokio::fs::read_to_string(file_path).await.map_err(|e| {
        wms_common::WmsError::StorageError(format!("Failed to read stations file: {}", e))
    })?;

    let locations = parse_stations_csv(&csv_data)?;

    info!(
        file = file_path,
        count = locations.len(),
        "Loading additional stations from file"
    );

    let mut inserted = 0;
    for chunk in locations.chunks(100) {
        inserted += catalog.upsert_locations(chunk).await?;
    }

    Ok(inserted)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_stations_csv() {
        let csv = r#"
# Test airport data
KJFK,John F Kennedy Intl,-73.7781,40.6413,4,NY
KLAX,Los Angeles Intl,-118.4085,33.9416,38,CA
KORD,Chicago O Hare Intl,-87.9073,41.9742,201,IL
"#;

        let locations = parse_stations_csv(csv).unwrap();
        assert_eq!(locations.len(), 3);

        let jfk = &locations[0];
        assert_eq!(jfk.id, "KJFK");
        assert_eq!(jfk.name, "John F Kennedy Intl");
        // Note: CSV has lon,lat order but Location stores lon,lat
        assert!((jfk.lon - (-73.7781)).abs() < 0.001);
        assert!((jfk.lat - 40.6413).abs() < 0.001);
        assert_eq!(jfk.elevation_m, Some(4.0));
        assert_eq!(jfk.region, Some("NY".to_string()));
    }

    #[test]
    fn test_parse_stations_csv_minimal() {
        let csv = "KDEN,Denver Intl,-104.6737,39.8561";
        let locations = parse_stations_csv(csv).unwrap();
        assert_eq!(locations.len(), 1);
        assert_eq!(locations[0].id, "KDEN");
        assert!(locations[0].elevation_m.is_none());
    }

    #[test]
    fn test_parse_populated_places_csv() {
        let csv = r#"# comment header
id,name,lon,lat,elevation_m,state,population
PP3651000,New York,-73.93868,40.66271,,NY,8258035
PP0644000,Los Angeles,-118.41083,34.01939,,CA,3820914
"#;
        let places = parse_populated_places_csv(csv).unwrap();
        assert_eq!(places.len(), 2);

        let nyc = &places[0];
        assert_eq!(nyc.id, "PP3651000");
        assert_eq!(nyc.name, "New York");
        assert!((nyc.lon - (-73.93868)).abs() < 1e-5);
        assert!((nyc.lat - 40.66271).abs() < 1e-5);
        assert_eq!(nyc.location_type, Some("populated_place".to_string()));
        assert_eq!(nyc.country, Some("US".to_string()));
        assert_eq!(nyc.region, Some("NY".to_string()));
        assert!(nyc.elevation_m.is_none());
        // population + state stored in properties
        assert_eq!(nyc.properties["population"], serde_json::json!(8258035));
        assert_eq!(nyc.properties["state"], serde_json::json!("NY"));
    }

    #[test]
    fn test_split_csv_line_quoted() {
        let parts = split_csv_line(
            r#"PP1234132,"Islamorada, Village of Islands",-80.54330,24.98435,,FL,6988"#,
        );
        assert_eq!(parts.len(), 7);
        assert_eq!(parts[0], "PP1234132");
        assert_eq!(parts[1], "Islamorada, Village of Islands");
        assert_eq!(parts[2], "-80.54330");
        assert_eq!(parts[5], "FL");
        assert_eq!(parts[6], "6988");
    }

    #[test]
    fn test_parse_populated_places_quoted_names() {
        let csv = concat!(
            "id,name,lon,lat,elevation_m,state,population\n",
            "PP1234132,\"Islamorada, Village of Islands\",-80.54330,24.98435,,FL,6988\n",
        );
        let places = parse_populated_places_csv(csv).unwrap();
        assert_eq!(places.len(), 1);
        assert_eq!(places[0].name, "Islamorada, Village of Islands");
        assert_eq!(places[0].properties["population"], serde_json::json!(6988));
    }

    #[test]
    fn test_parse_populated_places_embedded() {
        // The committed dataset should parse cleanly and contain major cities.
        let places = parse_populated_places_csv(EMBEDDED_POPULATED_PLACES_CSV).unwrap();
        assert!(places.len() > 5000, "expected thousands of places");
        assert!(places.iter().any(|p| p.name == "New York"));
        assert!(places
            .iter()
            .all(|p| p.location_type.as_deref() == Some("populated_place")));
    }

    #[test]
    fn test_parse_stations_csv_with_comments() {
        let csv = r#"
# Header comment
KABC,Test Airport,-100.0,40.0,100

# Another comment
KXYZ,Another Airport,-90.0,35.0,50
"#;

        let locations = parse_stations_csv(csv).unwrap();
        assert_eq!(locations.len(), 2);
    }
}
