#!/usr/bin/env python3
"""
Build crates/storage/data/us_zip_codes.csv for ZIP-code lookup in the EDR
`populated` collection.

Source (public domain):
  Census 2023 ZCTA Gazetteer (national), a zip archive containing
  2023_Gaz_zcta_national.txt with columns:
    GEOID(=ZCTA5/ZIP), ALAND, AWATER, ..., INTPTLAT, INTPTLONG
  https://www2.census.gov/geo/docs/maps-data/data/gazetteer/2023_Gazetteer/

We keep only the 5-digit ZIP and its interior-point lat/lon. ZIPs carry no
name/state in this file; the API labels them at query time with the nearest
populated place (reusing the existing spatial lookup), so no fragile ZIP->city
crosswalk is needed here.

US-focused: territory ZIPs (Puerto Rico 006xx-009xx, VI 008xx, etc.) are
dropped to match the CONUS/forecast focus of the collection.

Output columns (LON,LAT order = GeoJSON convention):
  id,zip,lon,lat

  id = "ZIP" + 5-digit code (e.g. ZIP80202 = Denver, CO)

Run:  python3 scripts/build_zip_codes.py
(Requires network access to census.gov; output is committed to the repo.)
"""

import csv
import io
import sys
import urllib.request
import zipfile
from pathlib import Path

ZCTA_ZIP_URL = (
    "https://www2.census.gov/geo/docs/maps-data/data/gazetteer/"
    "2023_Gazetteer/2023_Gaz_zcta_national.zip"
)

# Territory ZIP prefixes to exclude (not covered by CONUS/AK/HI forecast grids
# in a useful way, and not US states). 006-009 = PR/VI, 969 = GU/MP/etc.,
# 008 = VI. AK (995-999) and HI (967-968) are kept.
TERRITORY_PREFIXES = ("006", "007", "008", "009", "969")


def fetch_zcta_text() -> str:
    print(f"  fetching {ZCTA_ZIP_URL}", file=sys.stderr)
    req = urllib.request.Request(
        ZCTA_ZIP_URL, headers={"User-Agent": "weather-wms-build"}
    )
    with urllib.request.urlopen(req, timeout=120) as r:
        raw = r.read()
    zf = zipfile.ZipFile(io.BytesIO(raw))
    # The archive contains a single .txt
    name = next(n for n in zf.namelist() if n.endswith(".txt"))
    with zf.open(name) as f:
        return f.read().decode("utf-8")


def main():
    print("Building ZIP-code dataset...", file=sys.stderr)
    text = fetch_zcta_text()

    rows = []
    reader = csv.reader(io.StringIO(text), delimiter="\t")
    header = next(reader, None)
    if not header:
        print("empty ZCTA file", file=sys.stderr)
        sys.exit(1)

    for row in reader:
        if len(row) < 7:
            continue
        zip_code = row[0].strip()
        if len(zip_code) != 5 or not zip_code.isdigit():
            continue
        if zip_code.startswith(TERRITORY_PREFIXES):
            continue
        try:
            lat = float(row[5].strip())
            lon = float(row[6].strip())
        except ValueError:
            continue
        rows.append(
            {
                "id": f"ZIP{zip_code}",
                "zip": zip_code,
                "lon": f"{lon:.5f}",
                "lat": f"{lat:.5f}",
            }
        )

    # Sort by ZIP for a human-scannable, stable file
    rows.sort(key=lambda r: r["zip"])

    out_path = (
        Path(__file__).resolve().parent.parent
        / "crates" / "storage" / "data" / "us_zip_codes.csv"
    )
    with open(out_path, "w", newline="\n") as f:
        f.write(
            "# US ZIP codes (Census 2023 ZCTA Gazetteer interior points)\n"
            "# id = ZIP<5-digit>; LON,LAT order; territories excluded\n"
            "# Generated by scripts/build_zip_codes.py\n"
        )
        writer = csv.DictWriter(
            f, lineterminator="\n", fieldnames=["id", "zip", "lon", "lat"]
        )
        writer.writeheader()
        for r in rows:
            writer.writerow(r)

    print(f"Wrote {len(rows)} ZIP codes to {out_path}", file=sys.stderr)


if __name__ == "__main__":
    main()
